home:
  value_item_movie_new: 24
  value_item_movie_update: 9
  value_item_movie_series: 4
sessions:
  login_success:
    remember: "1"
    forget: "0"
  check_login:
    admin : "admin"
    user: "user"
user:
  max_last_name: 255
  max_first_name: 255
  max_email: 255
  min_password: 6
movie_type:
  value_year: 2014
  value_select: 5
  value_item_movie: 16
  value_select_year: 2
header:
  year_0: 0
  year_1: 1
  year_2: 2
  year_3: 3
  year_4: 4
  year_5: 5
admin:
  movies:
    index:
      number_page: 7
movie:
  max_name: 255
  min_content: 1
producer:
  max_name: 255
  max_email: 255
status: 1
total_episode: 25
watch_movie:
  value_item: 5
  split_equal: "="
  split_share: "/"
  split_ask: "?"
  url: "//ok.ru/videoembed/"
episode:
  max_name: 255
  max_link: 1000
